### ISSUE TITLE
Backquote broken on SBCL again for defmacro/g!

### ISSUE THREAD

**Issue by equwal** [thephoeron/let-over-lambda#16]
`defmacro/g!` and friends don't work on SBCL 1.4.1 as far as I can tell.
I've implemented the functionality using a reader macro, and can probably do it for defmacro! also. Maybe that would be a better route than having to track SBCL's development. Let me know what you think about this.

**Comment by thephoeron** [comment]
Thanks for letting me know! I'll profile backquote expansion across recent versions of SBCL, and double-check the book for the intended semantics. In the mean time, I would be happy to hear more about the reader-macro strategy you have in mind.

**Comment by thephoeron** [comment]
Cf., Pull-Request #17

**Comment by equwal** [comment]
I wanted to be able to work with the code in the book, and the reader macros made it happen. If you find how to do another hack against the SBCL compiler, that might be better. The macros work like this: take something like `defmacro! mac (o!x) ...` and replace it with `#d{mac (o!x)...}`. So it is really just a drop in replacement. It isn't perfect yet, but it is better than not being able to use the code on SBCL at all.

**Comment by thephoeron** [comment]
> Just chiming in since it seems like #17 is bust, I managed to get defmacro/g! working by using the named read table from fare-quasiquote-extras as suggested by https://www.reddit.com/r/lisp/comments/11917mf/comment/j9k8yg1

Good to know, I'll check that thread out and see what can be done.

This may help with some of my other libraries as well.

**Comment by thephoeron** [comment]
> Just chiming in since it seems like #17 is bust, I managed to get defmacro/g! working by using the named read table from fare-quasiquote-extras as suggested by https://www.reddit.com/r/lisp/comments/11917mf/comment/j9k8yg1

Want to give the latest a try? the `:LOL-SYNTAX` readtable now includes `:FARE-QUASIQUOTE`.

I should also now be able to strip away the special handling of `FLATTEN` and other SBCL-specific issues. 🤘🏻

**Comment by equwal** [comment]
nice to see this thing move after only five years
