### ISSUE TITLE
Sharp-backquote changes break perlre

### ISSUE THREAD

**Issue by quicklisp** [thephoeron/let-over-lambda#8]
I'm not sure which project is responsible for fixing things, but some new change to let-over-lambda has broken perlre.

https://github.com/jschatzer/perlre/issues/1 has the details. Basically, perlre is using the sharp-backquote read macro but it is no longer available.

**Comment by thephoeron** [comment]
@quicklisp: thanks, I'll look into the changeset from @EuAndreh --- when had you planned the next release for?

**Comment by quicklisp** [comment]
I hope to make a new release this weekend. I usually try to make my updates on the first weekend of the month.

**Comment by EuAndreh** [comment]
I'll check for what happened.

**Comment by EuAndreh** [comment]
I believe that he was using the read-macro with no previous setup because the previous version of `let-over-lambda` modified the `*readtable*` globally.

I just made a pull request to fix it.

**Comment by EuAndreh** [comment]
I believe that jschatzer fixed the issue.

This can be closed.

**Comment by thephoeron** [comment]
Excellent. @quicklisp does everything build correctly for you now?

**Comment by quicklisp** [comment]
Everything builds together fine now, thanks.

**Comment by thephoeron** [comment]
Great. Thanks everyone!
